### ISSUE TITLE
Doesnt wails use webview2 on windows?

### ISSUE THREAD

**Issue by piotr-grzegorzek** [Elanis/web-to-desktop-framework-comparison#611]
https://wails.io/docs/guides/windows/

column "Engine" in this repo says it uses webkit only.

**Comment by Elanis** [comment]
I don't know a lot about wails myself, so I don't really know how it works under the hood.
It's weird because here: https://wails.io/docs/howdoesitwork they only talk about webkit ... And in the introduction, they indeed talk about Webview2: https://wails.io/docs/introduction/

Also, on Linux, they talk about webkitgtk: https://wails.io/docs/guides/linux

So they probably are using Webview2 and webkitgtk like Tauri ?
What do you think ?

**Comment by leaanthony** [comment]
Wails uses WebKit2gtk on Linux, Webview2 on Windows and WkWebview on Mac.

**Comment by Elanis** [comment]
Oh, thanks @leaanthony !
Glad we can help :)

I will modify this then !
